### ISSUE TITLE
how it works ?

### ISSUE THREAD

**Issue by alucard13s** [giannitedesco/project-mayhem#6]
hi, i don't understand how it works. i have installed python software (first time i use this) but how i launch the program ? there's no tutorial for newbies. i have to launch by command ? If someone can help me, i use windows 8.1.
Thanks in advance

**Comment by giannitedesco** [comment]
Try the README on the main page. It's not just python software, it's C software and there is no windows port. Furthermore, check the date of last commit, it's about 5 years ago. The HTML we scrape has changed and therefore the GUI doesn't work any more.
